name: Deploy to Azure and Collect Code Coverage

on:
  push:
    branches:
      - master  # Dispara o workflow ao realizar push na branch "developer"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Ajuste conforme sua versão

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and collect code coverage
      run: |
        # Executa os testes e coleta a cobertura de código no diretório especificado
        dotnet test --collect:"XPlat Code Coverage"

    - name: Publish the app
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "APP-LeandroSerra-API"  # Nome do App Service
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish

    - name: Upload test results and coverage as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-results
